# Generated by Django 3.2.5 on 2024-02-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(choices=[(0, ''), (1, '*'), (2, '**'), (3, '***'), (4, '****')], default=1),
        ),
    ]
